import{A as M,S as A,N as O,a as L}from"./assets/vendor-ClQ9ArOj.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(o){if(o.ep)return;o.ep=!0;const s=n(o);fetch(o.href,s)}})();let m=3;const w=document.querySelector(".load-more");w.addEventListener("click",e=>{const t=document.querySelectorAll(".project-list .visually-hidden");for(const n of t)if(m++,m>7&&w.classList.add("visually-hidden"),n.classList.remove("visually-hidden"),m==6)return});document.addEventListener("DOMContentLoaded",()=>{new M("#ac-list",{closeOther:!0}).open(0)});const B=document.querySelector(".swiper-wrapper"),y=document.querySelector(".error-text"),c=document.querySelector(".swiper-button-prev"),l=document.querySelector(".swiper-button-next"),g=document.querySelector(".slider-icon"),P=async()=>{try{const e=await L.get("https://portfolio-js.b.goit.study/api/reviews");return y.style.display="none",e.data}catch(e){y.style.display="block",c.style.display="none",l.style.display="none",console.log(e)}},j=e=>e.map(t=>`
        <div class='swiper-slide'>
        <li class='review-card'>
            <p class='review-text'>${t.review}</p>
            <div class='author-info'>
                <img src='${t.avatar_url}' alt='${t.author}' class='review-img'/>
                <p class='review-author'>${t.author}</p>
            </div>
        </li>
        </div>
    `).join(""),N=async()=>{const e=await P();if(!e){y.style.display="block",c.style.display="none",l.style.display="none";return}const t=j(e);B.insertAdjacentHTML("beforeend",t);const n=r=>{r.isBeginning?c.classList.add("disabled"):(c.classList.remove("disabled"),c.style.transition="all .3s ease-out allow-discrete",g.style.transition="all .3s ease-out allow-discrete"),r.isEnd?(l.classList.add("disabled"),l.style.transition="all .3s ease-out allow-discrete",g.style.transition="all .3s ease-out allow-discrete"):l.classList.remove("disabled")};new A(".swiper",{modules:[O],slidesPerView:1,spaceBetween:20,direction:"horizontal",navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},centeredSlides:!0,on:{init:function(){n(this)},slideChange:function(){n(this)}},breakpoints:{768:{slidesPerView:1,spaceBetween:32},1280:{spaceBetween:32,centeredSlides:!1,slidesPerView:2}}})};N();const b=document.querySelector("#modal"),S=document.querySelectorAll("[data-close-modal]");function T(){b.classList.add("is-open"),S.forEach(e=>{e.addEventListener("click",h),document.addEventListener("keydown",E)})}function h(){b.classList.remove("is-open"),document.body.style.overflow="",S.forEach(e=>{e.removeEventListener("click",h),document.removeEventListener("keydown",E)})}function E(e){e.key==="Escape"&&h()}const a=document.querySelector("#cont-form");a.addEventListener("submit",async e=>{e.preventDefault();const t=document.querySelector("#modal .title-modal"),n=document.querySelector("#modal .desc"),r={email:a.elements["user-email"].value.trim(),comment:a.elements["user-message"].value.trim()};try{const o=await L.post("https://portfolio-js.b.goit.study/api/requests",r);a.reset(),T(),document.body.style.overflow="hidden";const{title:s,message:i}=o.data;t.innerHTML=s,n.innerHTML=i}catch{alert("Failed to submit the form. Try again.")}});const f=document.querySelector(".mob-menu"),d=document.querySelector("#header .js-open-menu"),k=document.querySelectorAll('.mob-menu [data-close="true"]');d.addEventListener("click",q);function q(){d.classList.toggle("is-active"),f.classList.toggle("is-open"),f.classList.contains("is-open")?document.body.style.overflow="hidden":document.body.style.overflow="",k.forEach(e=>{e.addEventListener("click",x)})}function x(){document.body.style.overflow="",d.classList.remove("is-active"),f.classList.remove("is-open"),d.addEventListener("click",q),k.forEach(e=>{e.removeEventListener("click",x)})}const W=document.querySelector("html"),v=document.querySelectorAll('[name="checkbox-mod"]'),p=localStorage.getItem("theme");p&&(p==="theme-dark"?u("theme-light","theme-dark"):u("theme-dark","theme-light"),v.forEach(e=>{e.checked=p==="theme-dark"}));function u(e,t){W.classList.replace(e,t),localStorage.setItem("theme",t),v.forEach(n=>{n.checked=t==="theme-dark"})}v.forEach(e=>{e.addEventListener("change",t=>{t.target.checked?u("theme-light","theme-dark"):u("theme-dark","theme-light")})});
//# sourceMappingURL=index.js.map
